---
dist: trusty
before_install:
  - sudo ./scripts/1-add-repos.sh
install:
  - sudo ./scripts/2-install-dependencies.sh
before_script:
  # Download plot script from spencers gists. Intentionally hosted externally so it is consistant accross commits/builds
  - sudo ./scripts/3-download-scripts.sh
script:
  - sudo ./scripts/4-current-pdf.sh
  # Checkout previous commit # TODO() Make this more resiliant to multi commit tests
  - git checkout HEAD^1
  - sudo ./scripts/5-previous-pdf.sh
  - sudo ./scripts/6-convert-files.sh
  - sudo ./scripts/7-generate-diffs.sh

addons:
  artifacts:
    paths:
      - $(ls /tmp/diff/*.png | tr "\n" ":")
  s3_region: "US Standard"